import type { Link, Visit } from './types'

function v(
  mins: number,
  country: string,
  cc: string,
  flag: string,
  city: string,
  ip: string,
  device: string,
  browser: string,
  result: 'allow' | 'blocked'
): Visit {
  return { mins, country, cc, flag, city, ip, device, browser, result }
}

export const mockLinks: Link[] = [
  {
    id: 'lk1',
    alias: 'q4-report',
    destination: 'https://drive.google.com/file/d/1aZx9kQ/view',
    password: 'phoenix',
    limit: 100,
    used: 47,
    expiry: 'in 12 days',
    oneTime: false,
    geo: null,
    notify: true,
    status: 'active',
    daily: [4, 9, 6, 13, 8, 11, 5],
    visits: [
      v(7, 'United States', 'US', '🇺🇸', 'San Francisco', '192.0.2.41', 'MacBook · macOS', 'Chrome 126', 'allow'),
      v(54, 'Germany', 'DE', '🇩🇪', 'Berlin', '198.51.100.7', 'ThinkPad · Linux', 'Firefox 127', 'allow'),
      v(132, 'United States', 'US', '🇺🇸', 'New York', '203.0.113.9', 'iPhone · iOS', 'Safari 17', 'allow'),
      v(310, 'India', 'IN', '🇮🇳', 'Bengaluru', '192.0.2.88', 'Pixel · Android', 'Chrome 125', 'allow'),
      v(420, 'Unknown', '??', '🏴', '— (VPN exit)', '10.0.0.1', '—', '—', 'blocked'),
    ],
  },
  {
    id: 'lk2',
    alias: 'beta-invite',
    destination: 'https://privly.app/signup?ref=beta',
    password: null,
    limit: 50,
    used: 50,
    expiry: 'in 4 days',
    oneTime: false,
    geo: null,
    notify: false,
    status: 'limit',
    daily: [12, 9, 8, 7, 6, 5, 3],
    visits: [
      v(20, 'United States', 'US', '🇺🇸', 'Austin', '203.0.113.22', 'MacBook · macOS', 'Arc 1.4', 'allow'),
      v(95, 'Canada', 'CA', '🇨🇦', 'Toronto', '198.51.100.40', 'iPad · iOS', 'Safari 17', 'allow'),
      v(140, 'United Kingdom', 'GB', '🇬🇧', 'London', '192.0.2.200', 'Surface · Windows', 'Edge 126', 'allow'),
      v(180, 'United States', 'US', '🇺🇸', 'Denver', '203.0.113.5', '—', 'Chrome 126', 'blocked'),
    ],
  },
  {
    id: 'lk3',
    alias: 'press-kit',
    destination: 'https://dropbox.com/sh/presskit-2026',
    password: null,
    limit: null,
    used: 218,
    expiry: 'expired',
    oneTime: false,
    geo: null,
    notify: false,
    status: 'expired',
    daily: [30, 42, 38, 51, 24, 18, 0],
    visits: [
      v(1440, 'France', 'FR', '🇫🇷', 'Paris', '198.51.100.61', 'MacBook · macOS', 'Safari 17', 'allow'),
      v(1600, 'Japan', 'JP', '🇯🇵', 'Tokyo', '192.0.2.150', 'iPhone · iOS', 'Chrome 126', 'allow'),
      v(2880, 'Brazil', 'BR', '🇧🇷', 'São Paulo', '203.0.113.71', '— · Android', 'Chrome 125', 'allow'),
    ],
  },
  {
    id: 'lk4',
    alias: 'nda-draft',
    destination: 'https://docs.google.com/document/d/1p9Q/edit',
    password: 'redwood',
    limit: null,
    used: 0,
    expiry: 'no expiry',
    oneTime: true,
    geo: null,
    notify: true,
    status: 'armed',
    daily: [0, 0, 0, 0, 0, 0, 0],
    visits: [],
  },
  {
    id: 'lk5',
    alias: 'wallet-seed',
    destination: 'https://vault.privly.app/s/9fA2k',
    password: 'glacier',
    limit: 1,
    used: 1,
    expiry: 'no expiry',
    oneTime: true,
    geo: null,
    notify: true,
    status: 'burned',
    daily: [0, 0, 0, 0, 0, 1, 0],
    visits: [
      v(180, 'United States', 'US', '🇺🇸', 'Seattle', '203.0.113.88', 'MacBook · macOS', 'Brave 1.6', 'allow'),
    ],
  },
  {
    id: 'lk6',
    alias: 'team-roster',
    destination: 'https://notion.so/team-roster-q3',
    password: null,
    limit: null,
    used: 36,
    expiry: 'no expiry',
    oneTime: false,
    geo: 'US, CA',
    notify: false,
    status: 'active',
    daily: [6, 4, 7, 5, 9, 3, 2],
    visits: [
      v(40, 'United States', 'US', '🇺🇸', 'Chicago', '192.0.2.31', 'MacBook · macOS', 'Chrome 126', 'allow'),
      v(88, 'Canada', 'CA', '🇨🇦', 'Vancouver', '198.51.100.12', 'ThinkPad · Linux', 'Firefox 127', 'allow'),
      v(150, 'Germany', 'DE', '🇩🇪', 'Munich', '203.0.113.44', '—', 'Chrome 126', 'blocked'),
    ],
  },
]
